---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      visual-app: grafana
      db-app: flask-server
  template:
    metadata:
      labels:
        visual-app: grafana
        db-app: flask-server
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
      - name: grafana
        image: grafana/grafana:8.4.4
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
            name: http-grafana
            protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /robots.txt
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: shared-data
      - name: flask
        image: gcr.io/PROJECT_ID/FLASK_SERVER_IMAGE:TAG
        volumeMounts:
        - name: shared-data
          mountPath: /var/lib/grafana
        env:
        - name: DB_DIR
          value: "/var/lib/grafana"
        ports:
        - containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-dpm
  labels:
    app: crawler-dpm
  namespace: default
spec:
  replicas: 8
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      imagePullSecrets: 
        - name: regcred
      containers:
      - name: crawler-ctn
        image: gcr.io/PROJECT_ID/CRAWLER_IMAGE:TAG
        ports:
        - containerPort: 7878
          name: crawler-p
        env:
          - name: SERVICE_HOST
            value: "flask-service"
          - name: SERVICE_PORT
            value: "5000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "500m"